### ISSUE TITLE
request for enhancement: support for INR (Indian Rupee ₹)

### ISSUE THREAD

**Issue by csj-github** [Delni/mercury#1]
It would be great if the mercury software could support Indian Rupee (Indian Rupee Symbol ₹) as an additional currency symbol.

**Comment by Delni** [comment]
I have added  some more currencies to mercury, including Indian Rupee. (commit [`71cb43`](https://github.com/Delni/mercury/commit/71cb43fe285d75d7ad7ef2f28ee884a2522e21bd))
However I won't make a release for minor enhancement as I am working on more changes.  If you want to test this asap, just clone the project and run `npm run dist` to generate executables files

**Comment by csj-github** [comment]
Thanks. I will check it out.
